from tflite_support.metadata_writers import image_segmenter
from tflite_support.metadata_writers import writer_utils


def save_model_with_metadata(tflite_model_path):
    ImageSegmenterWriter = image_segmenter.MetadataWriter

    NORMALIZATION_MEAN = 0.0
    NORMALIZATION_STD = 255.0

    writer = ImageSegmenterWriter.create_for_inference(
        writer_utils.load_file(tflite_model_path), [NORMALIZATION_MEAN], [NORMALIZATION_STD],
        [])

    # Verify the metadata generated by metadata writer.
    print(writer.get_metadata_json())


if __name__ == "__main__":
    save_model_with_metadata("/home/vaishak/Downloads/tflite/u2netlite/40.tflite")
